trigger: ["master"]
pr: ["master"]

jobs:
# Run build on oldest supported rust version. Do not change the rust
# version without a Github issue first.
#
# This job will also build and deploy the docs to gh-pages.
- template: ci/azure-test-stable.yml
  parameters:
    name: minrust
    rust_version: 1.36.0
    target: x86_64-unknown-linux-gnu
    os_name: linux
    test: true
