trigger: ["master"]
pr: ["master"]

jobs:
# Run build on oldest supported rust version. Do not change the rust
# version without a Github issue first.
#
# This job will also build and deploy the docs to gh-pages.
- template: ci/azure-test-stable.yml
  parameters:
    name: minrust
    rust_version: 1.36.0

# Stable
- template: ci/azure-test-stable.yml
  parameters:
    name: stable
    cross: true

# Run tests on some extra platforms
- template: ci/azure-cross-compile.yml
  parameters:
    name: cross

# Serde implementation
- template: ci/azure-test-stable.yml
  parameters:
    name: serde
    extra_args: "--features serde"

# 128 bit numbers
- template: ci/azure-test-stable.yml
  parameters:
    name: i128
    extra_args: "--features i128"

# `Either` impls
- template: ci/azure-test-stable.yml
  parameters:
    name: either
    extra_args: "--features either"

# Sanitizers
- template: ci/azure-tsan.yml
  parameters:
    name: tsan
    rust_version: nightly
