parameters:
  tests: true
  rust_version: stable
  extra_args: ""

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04

      ${{ if parameters.cross }}:
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{parameters.rust_version}}

  - script: cargo build $(extra_args)
    displayName: cargo build

  - ${{ if parameters.tests }}:
    - script: cargo test $(extra_args)
      displayName: cargo test

  - ${{ if parameters.benches }}:
    - script: cargo check --benches
      displayName: Check benchmarks
