parameters:
  tests: true
  rust_version: stable
  vmImage: ubuntu-16.04

jobs:
- job: ${{ parameters.name }}
  displayName: Cross
  strategy:
    matrix:
      i686:
        target: i686-unknown-linux-gnu
      armv7:
        target: armv7-unknown-linux-gnueabihf
      powerpc:
        target: powerpc-unknown-linux-gnu
        env:
          RUST_TEST_THREADS: 1
      powerpc64:
        target: powerpc64-unknown-linux-gnu
        env:
          RUST_TEST_THREADS: 1
  pool:
    vmImage: $(vmImage)

  steps:
    - template: azure-install-rust.yml
      parameters:
        rust_version: stable

    - script: rustup target add $(target)
      displayName: Add target

    - script: cargo build --target $(target)
      displayName: cargo build

    - ${{ if parameters.test }}:
      - script: cargo test --target $(target)
        displayName: cargo test
